# Homebrew packages — declared in Nix, rendered to a Brewfile and applied
# automatically via `brew bundle` during home-manager activation.

{
  config,
  lib,
  pkgs,
  ...
}:

let
  formulae = [
    "aws-sso-util"
    "awscli"
    "broot"
    "cabal-install"
    "curl"
    "direnv"
    "fd"
    "fzf"
    "gh"
    "git"
    "graphviz"
    "htop"
    "kubernetes-cli"
    "minikube"
    "nixfmt"
    "node@22"
    "nss"
    "openbao"
    "prettier"
    {
      name = "redis";
      restartService = true;
    }
    "rg"
    "starship"
    "tmux"
    "tree"
    "watchman"
    "wget"
  ];

  taps = [
    {
      name = "bellroy/tap";
      trusted = true;
    }
  ];

  brews = [
    "gitapult"
    "config-rules-cli"
    "byproduct"
    "powerful-owl"
    "iam-cli"
  ];

  casks = [
    "activitywatch@experimental"
    "claude-code@latest"
    "dbeaver-community"
    "docker-desktop"
    "font-fira-code"
    "font-fira-mono"
    "gcloud-cli"
    "handbrake-app"
    "obsidian"
    "orbstack"
    "postgres-app"
    "rectangle"
    "spotify"
    "wealthfolio"
    "whatsapp"
    "zed"
  ];

  renderFormula =
    f:
    if builtins.isString f then
      ''brew "${f}"''
    else if f.restartService or false then
      ''brew "${f.name}", restart_service: :changed''
    else
      ''brew "${f.name}"'';

  renderTap =
    t:
    if builtins.isString t then
      ''tap "${t}"''
    else if t.trusted or false then
      ''tap "${t.name}", trusted: true''
    else
      ''tap "${t.name}"'';

  brewfileContent = lib.concatStringsSep "\n" (
    [ "# This file is generated by home-manager from brew.nix — do not edit by hand." ]
    ++ map renderTap taps
    ++ map renderFormula formulae
    ++ map renderFormula brews
    ++ map (c: ''cask "${c}"'') casks
    ++ [ "" ] # trailing newline
  );
in
{
  home.file.".Brewfile".text = brewfileContent;

  home.activation.installHomebrew = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    if [[ ! -f /opt/homebrew/bin/brew && ! -f /usr/local/bin/brew ]]; then
      export PATH="/usr/bin:/bin:$PATH"
      $DRY_RUN_CMD /bin/bash -c "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
  '';

  home.activation.brewBundle = lib.hm.dag.entryAfter [ "installHomebrew" ] ''
    BREW_BIN=""
    if [[ -x /opt/homebrew/bin/brew ]]; then
      BREW_BIN=/opt/homebrew/bin/brew
    elif [[ -x /usr/local/bin/brew ]]; then
      BREW_BIN=/usr/local/bin/brew
    fi

    GH_BIN=""
    if [[ -x /opt/homebrew/bin/gh ]]; then
      GH_BIN=/opt/homebrew/bin/gh
    elif [[ -x /usr/local/bin/gh ]]; then
      GH_BIN=/usr/local/bin/gh
    fi

    if [[ -n "$BREW_BIN" ]]; then
      if [[ -n "$GH_BIN" ]]; then
        export HOMEBREW_GITHUB_API_TOKEN="$("$GH_BIN" auth token 2>/dev/null)"
      fi
      $DRY_RUN_CMD "$BREW_BIN" bundle --file="${config.home.homeDirectory}/.Brewfile"
      $DRY_RUN_CMD "$BREW_BIN" upgrade --cask --greedy claude-code@latest || true
    fi
  '';
}
