# Homebrew packages — declared in Nix, rendered to a Brewfile
#
# After `home-manager switch`, install/sync with:
#   brew bundle --file=~/.Brewfile

{
  config,
  lib,
  pkgs,
  ...
}:

let
  formulae = [
    "awscli"
    "broot"
    "cabal-install"
    "curl"
    "direnv"
    "fzf"
    "gh"
    "git"
    "graphviz"
    "htop"
    "nixfmt"
    "node@22"
    "nss"
    "starship"
    "tmux"
    "tree"
    "watchman"
    "wget"
  ];

  casks = [
    "claude-code"
    "dbeaver-community"
    "docker"
    "font-fira-code"
    "font-fira-mono"
    "obsidian"
    "zed"
  ];

  brewfileContent = lib.concatStringsSep "\n" (
    [ "# This file is generated by home-manager from brew.nix — do not edit by hand." ]
    ++ map (f: ''brew "${f}"'') formulae
    ++ map (c: ''cask "${c}"'') casks
    ++ [ "" ] # trailing newline
  );
in
{
  home.file.".Brewfile".text = brewfileContent;
}
