# Homebrew packages — declared in Nix, rendered to a Brewfile and applied
# automatically via `brew bundle` during home-manager activation.

{
  config,
  lib,
  pkgs,
  ...
}:

let
  formulae = [
    "aws-sso-util"
    "awscli"
    "broot"
    "cabal-install"
    "curl"
    "direnv"
    "fzf"
    "gh"
    "git"
    "graphviz"
    "htop"
    "nixfmt"
    "node@22"
    "nss"
    "prettier"
    {
      name = "redis";
      restartService = true;
    }
    "starship"
    "tmux"
    "tree"
    "watchman"
    "wget"
  ];

  casks = [
    "claude-code"
    "dbeaver-community"
    "docker-desktop"
    "font-fira-code"
    "font-fira-mono"
    "handbrake-app"
    "obsidian"
    "orbstack"
    "postgres-app"
    "presentify"
    "rectangle"
    "spotify"
    "wealthfolio"
    "whatsapp"
    "zed"
  ];

  renderFormula =
    f:
    if builtins.isString f then
      ''brew "${f}"''
    else if f.restartService or false then
      ''brew "${f.name}", restart_service: :changed''
    else
      ''brew "${f.name}"'';

  brewfileContent = lib.concatStringsSep "\n" (
    [ "# This file is generated by home-manager from brew.nix — do not edit by hand." ]
    ++ map renderFormula formulae
    ++ map (c: ''cask "${c}"'') casks
    ++ [ "" ] # trailing newline
  );
in
{
  home.file.".Brewfile".text = brewfileContent;

  home.activation.installHomebrew = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    if [[ ! -f /opt/homebrew/bin/brew && ! -f /usr/local/bin/brew ]]; then
      export PATH="/usr/bin:/bin:$PATH"
      $DRY_RUN_CMD /bin/bash -c "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
  '';

  home.activation.brewBundle = lib.hm.dag.entryAfter [ "installHomebrew" ] ''
    BREW_BIN=""
    if [[ -x /opt/homebrew/bin/brew ]]; then
      BREW_BIN=/opt/homebrew/bin/brew
    elif [[ -x /usr/local/bin/brew ]]; then
      BREW_BIN=/usr/local/bin/brew
    fi
    if [[ -n "$BREW_BIN" ]]; then
      $DRY_RUN_CMD "$BREW_BIN" bundle --file="${config.home.homeDirectory}/.Brewfile"
    fi
  '';
}
